# Generated by Django 3.2.18 on 2023-04-14 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Time', models.TimeField(default=datetime.datetime(2023, 4, 14, 10, 30, 6, 647409))),
                ('payment_mode', models.TextField(default='', max_length=100)),
                ('payee_name', models.TextField(default='', max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Remark', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Time', models.TimeField(default=datetime.datetime(2023, 4, 14, 10, 30, 6, 647409))),
                ('payment_mode', models.TextField(default='', max_length=100)),
                ('payee_name', models.TextField(default='', max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('Remark', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabourAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('work_details', models.TextField(default='', max_length=100)),
                ('labour_id', models.IntegerField(default=0)),
                ('labour_name', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabourData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('labour_name', models.TextField(default='', max_length=100)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('labour_age', models.IntegerField(default=0)),
                ('labour_gender', models.TextField(default='', max_length=50)),
                ('salary', models.IntegerField(default=0)),
                ('work_details', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MachineryPurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('machinery_name', models.TextField(default='', max_length=100)),
                ('Rate', models.IntegerField(default=0)),
                ('Remark', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('Material_name', models.TextField(default='', max_length=100)),
                ('work_details', models.TextField(default='', max_length=200)),
                ('actual_qty', models.IntegerField(default=0)),
                ('Remarks', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentMachineryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('work_details', models.TextField(default='', max_length=100)),
                ('machinery_name', models.TextField(default='', max_length=100)),
                ('days', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('Details', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('site_name', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('actual_qty', models.IntegerField(default=0)),
                ('material_id', models.IntegerField(default=0)),
                ('Material_name', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('vehical_number', models.IntegerField(default=0)),
                ('Material_name', models.TextField(default='', max_length=100)),
                ('kilometer', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('Deliver_from', models.TextField(default='', max_length=100)),
                ('Deliver_To', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgreeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('site_id', models.IntegerField(default=0)),
                ('site_name', models.TextField(default='', max_length=100)),
                ('work_details', models.TextField(default='', max_length=100)),
                ('labour_id', models.IntegerField(default=0)),
                ('labour_name', models.TextField(default='', max_length=100)),
                ('Work_progress', models.TextField(default='', max_length=100)),
                ('Remark', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
