# Generated by Django 3.2.18 on 2023-04-14 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0003_auto_20230414_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='material_id',
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 14, 12, 10, 33, 987838)),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 14, 12, 10, 33, 987838)),
        ),
    ]
