# Generated by Django 3.2.18 on 2023-04-14 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_auto_20230414_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone_num', models.IntegerField(default=0)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 14, 13, 37, 3, 435293)),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 14, 13, 37, 3, 434283)),
        ),
    ]
