# Generated by Django 3.2.18 on 2023-04-21 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0005_auto_20230414_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensedata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='incomedata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labourattendance',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='labourdata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='machinerypurchasedata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materialsdata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rentmachinerydata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transportdata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workprogreedata',
            name='manager_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 21, 19, 45, 31, 524133)),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 21, 19, 45, 31, 524133)),
        ),
    ]
