# Generated by Django 3.2.18 on 2023-04-22 17:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mainpage', '0006_auto_20230421_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitedata',
            name='manager_id',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='manager_name',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='manager_user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 23, 15, 52, 239605)),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 23, 15, 52, 239605)),
        ),
    ]
