# Generated by Django 3.2.18 on 2023-04-22 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0008_auto_20230422_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 23, 18, 53, 425679)),
        ),
        migrations.AlterField(
            model_name='incomedata',
            name='Time',
            field=models.TimeField(default=datetime.datetime(2023, 4, 22, 23, 18, 53, 425679)),
        ),
    ]
